[versions]
kotlinx-serialization = "1.9.0"
kotlinx-io = "0.8.2"
kotest = "5.9.1"
okio = "3.16.4"
apache-avro = "1.12.1"
confluent-schema-registry = "8.1.1"
kotlinpoet = "2.2.0"
mockk = "1.14.6"
junit = "5.13.4"

[libraries]
apache-avro = { group = "org.apache.avro", name = "avro", version.ref = "apache-avro" }
confluent-kafka-avro-serializer = { group = "io.confluent", name = "kafka-avro-serializer", version.ref = "confluent-schema-registry" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotest-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }