[versions]
kotlin = "2.1.21"
kotlinxSerialization = "1.8.1"
kotlinx-io = "0.8.0"
kotestVersion = "5.9.1"
okio = "3.15.0"
apache-avro = "1.11.4"
mockk = "1.14.5"

[libraries]
apache-avro = { group = "org.apache.avro", name = "avro", version.ref = "apache-avro" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotest-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotestVersion" }
kotest-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotestVersion" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version = "2.0.0" }
github-versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
spotless = { id = "com.diffplug.spotless", version = "7.2.1" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.1" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }